version: '3.8'

services:
  database:
    container_name: skyscope-postgres-development
    hostname: postgres
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
