name: Deploy

permissions:
  contents: write
  id-token: write

on:
  push:
    branches: [ main ]

env:
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: |
          npm i -g @semantic-release/changelog @semantic-release/git semantic-release
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: semantic-release

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: release

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: actions/checkout@v4

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Docker image
        run: |
          echo $GOOGLE_CREDENTIALS > key.json
          gcloud auth activate-service-account --key-file key.json
          gcloud auth configure-docker us-east4-docker.pkg.dev
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          git checkout $LATEST_TAG
          docker build -t skyscopeapi:$LATEST_TAG .
          docker tag skyscopeapi:$LATEST_TAG us-east4-docker.pkg.dev/skyscopeapp/container-registry/skyscopeapi:$LATEST_TAG 
          docker tag skyscopeapi:$LATEST_TAG us-east4-docker.pkg.dev/skyscopeapp/container-registry/skyscopeapi:latest
          docker push us-east4-docker.pkg.dev/skyscopeapp/container-registry/skyscopeapi --all-tags
          gcloud run services update main-skyscope-api --image=us-east4-docker.pkg.dev/skyscopeapp/container-registry/skyscopeapi:$LATEST_TAG --region=us-east4 --project=skyscopeapp